services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - backend/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: node
    build: ./backend
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - backend/.env

  next-app:
    container_name: next-app
    build: ./frontend
    ports:
      - 3000:3000

  nginx:
    container_name: nginx_app
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - postgres
      - node
      - next-app

volumes:
  postgres-volume: