name: Pull Request on Github
on: [pull_request]
jobs:
  PullRequest-Github:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_PORT: 5000
          envkey_DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/names?schema=public"
          envkey_POSTGRES_USERNAME: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "names"
          directory: back-end
          file_name: .env.test
          fail_on_empty: true
      - name: Run tests
        run: docker compose -f docker-compose-tests.yml run api npm run test